#! /bin/bash

if !(hash git 2>/dev/null); then
  sudo apt-get install -y git
fi

if !(hash node 2>/dev/null); then
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi

if !(hash pm2 2>/dev/null); then
  sudo npm i -g pm2
fi
